### ISSUE TITLE
Comment email field conflict

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#46]
Hi Chris,

There is a conflict between the field on dabase comments table ("mail") and the field in the form theme_node_comments_form.ctp ("email").

I noted a strange behavior changing a comment settings on a content type. I discovered the problem of the email adding a new comment on an article page, the article content had this property "anonymous posters must leave their comment information" so email field cannot be saved (and so the whole comment). A my new content  type was created wit the property "anonymous posters may not enter their comment information", so the comments could be saved (without email address), but after changing this property to "anonymous posters must leave their comment information" the behavior was as previous (it seems that cached the property or maybe there is something the fact that initially the email and website could not be inserted) and comments could be saved (without email address). I test more and I try to find the problem...

**Comment by Gabri** [comment]
There are also two a problems with avatar in comments

1.
in theme_comment.ctp if I am an anonymous user (and I entered a comment) I have $comment['User'] set as:
array(
    'id' => null,
    'username' => null,
    'name' => null,
    'email' => null,
    'avatar' => null
)
and the condition (on line #8) if (isset($comment['User'])) is always passed.
1. a typo: on line #11 you need to add "echo" before $this->Layout->userAvatar ...otherwise no images!  ;)

**Comment by quickapps** [comment]
This should solve the avatar issue:
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/7a223aeeecf4ceb3aa80fd24f299f4d9a74e7405

I'll take a look to the comment email field issue

**Comment by Gabri** [comment]
Unfortunately adding "&& !empty($comment['User'])" doesn't fix the problem because $comment['User'] isn't empty for php.
"array_filter($comment['User'])" can do the trick, anyway due to the limitation of "empty" we cannot write "!empty(array_filter($comment['User']))" otherwise we'll get an error. We should use two steps like this:
1. $commentUserFiltered = array_filter($comment['User']);
2. ... !empty($commentUserFiltered)

so a better solution, because an empty array will evaluate to false, we can just write:
"if (isset($comment['User']) && array_filter($comment['User'])) {"

**Comment by quickapps** [comment]
Well, in that case `!empty($comment['User']['id'])` should do the same and faster than array_filter:
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/2f0918c523b511b165e93d47670f8bf5f9b16e9e
